const DATE_FORMAT = 'dd-LL-yyyy'
const SUBSCRIPTION_DURATION_DAYS = 30

// VUE
const VUE_DROPDOWN_EXTRA_ITEM_VALUE = -1

module.exports = {
  DATE_FORMAT: DATE_FORMAT,
  SUBSCRIPTION_DURATION_DAYS: SUBSCRIPTION_DURATION_DAYS,
  VUE_DROPDOWN_EXTRA_ITEM_VALUE: VUE_DROPDOWN_EXTRA_ITEM_VALUE
}
